from functools import partial

def set_generated_rules(el_world, el_set_rule):
    player = el_world.player
    fn = partial(el_set_rule, el_world)

    # Locations

    fn("Abyss_01_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Abyss01Top', player))
    fn("Abyss_01_GAMEPLAY.BP_SCR_LV2M_2171_2", lambda state: state.has('Abyss01Bottom', player))
    fn("Abyss_02_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('Abyss02Top', player) and (state.has('claw', player) and state.has('2LEDGE', player) or state.has('LEDGE', player) and state.has('HORIZONTAL', player)))
    fn("Abyss_02_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Abyss02Top', player))
    fn("Abyss_02_GAMEPLAY.BP_Interactable_Item_Tip4", lambda state: state.has('Abyss02Top', player))
    fn("Abyss_02_GAMEPLAY.BP_Interactable_Passive_healcountup_2", lambda state: state.has('Abyss02Top', player))
    fn("Abyss_04_GAMEPLAY.BP_SCR_LV1L_2170_2", lambda state: state.has('Abyss04Top', player) and state.has('mask', player) and state.has('slam', player) and state.has('hook', player) and state.has('3HEAL', player) and state.has('dash', player))
    fn("Abyss_04_GAMEPLAY.BP_SCR_LV1L_2170_3", lambda state: state.has('Abyss04Top', player) and state.has('mask', player) and state.has('slam', player) and state.has('hook', player) and state.has('3HEAL', player) and state.has('dash', player))
    fn("Abyss_05_GAMEPLAY.BP_Interactable_Item_FinalPassivePart_2", lambda state: state.has('Abyss05Top', player))
    fn("Abyss_05_GAMEPLAY.BP_Interactable_Item_Tip4", lambda state: state.has('Abyss05Top', player))
    fn("Abyss_05_GAMEPLAY.BP_SCR_LV3S_5000_1", lambda state: state.has('Abyss05Top', player))
    fn("Castle_01_GAMEPLAY.BP_e2082_Dog", lambda state: state.has('Castle01Left', player) or state.has('Castle01Right1', player) or state.has('Castle01Top', player) or state.has('Castle01Right2', player))
    fn("Castle_01_GAMEPLAY.BP_Interactable_Passive_healcountup_4", lambda state: state.has('Castle01Right2', player) and (state.has('LEDGE', player) or state.has('HORIZONTAL', player)))
    fn("Castle_01_GAMEPLAY.BP_Interactable_Passive_Spirit_StunStaminaDamageUp_2", lambda state: state.has('Castle01Right1', player) or state.has('Castle01Top', player))
    fn("Castle_01_GAMEPLAY.BP_SCR_LV1L_2031_2", lambda state: state.has('Dog', player) and state.has('CHARGE', player))
    fn("Castle_01_GAMEPLAY.BP_SCR_LV2M_2001_2", lambda state: state.has('Dog', player) and state.has('CHARGE', player))
    fn("Castle_02_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('Castle02Top', player))
    fn("Castle_02_GAMEPLAY.BP_SCR_LV1M_2000_3", lambda state: state.has('Castle02Top', player) and state.has('hook', player))
    fn("Castle_03_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: (state.has('Castle03Top1', player) or state.has('Castle03Top2', player)) and (state.has('hook', player) or state.has('claw', player) or state.has('HORIZONTAL', player) or state.has('dash', player) or state.has('LEDGE', player)))
    fn("Castle_03_GAMEPLAY.BP_SCR_LV1M_2001_2", lambda state: (state.has('Castle03Top1', player) or state.has('Castle03Top2', player)) and (state.has('hook', player) or state.has('claw', player) or state.has('LEDGE', player) and state.has('HORIZONTAL', player)))
    fn("Castle_04_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Castle04Top', player))
    fn("Castle_06_GAMEPLAY.BP_Interactable_Passives_Treasure_2", lambda state: state.has('Castle06Top', player))
    fn("Castle_06_GAMEPLAY.BP_SCR_LV1L_2030_3", lambda state: state.has('Castle06Right', player) and state.has('claw', player))
    fn("Castle_07_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Castle07Right', player) or state.has('Castle07Left', player))
    fn("Castle_08_GAMEPLAY.BP_Interactable_Item_PassiveSlot_2", lambda state: state.has('Castle08Top', player) and state.has('claw', player) and (state.has('LEDGE', player) or state.has('HORIZONTAL', player)))
    fn("Castle_08_GAMEPLAY.BP_Interactable_Passive_expup_5", lambda state: state.has('Castle08Top', player))
    fn("Castle_08_GAMEPLAY.BP_SCR_LV1M_2000_2", lambda state: state.has('Castle08Top', player))
    fn("Castle_08_GAMEPLAY.BP_SCR_LV1M_2000_3", lambda state: state.has('Castle08Top', player))
    fn("Castle_08_GAMEPLAY.BP_SCR_LV1S_2010_3", lambda state: state.has('Castle08Right', player))
    fn("Castle_09_GAMEPLAY.BP_SCR_LV2M_2000_3", lambda state: state.has('Castle09Left', player) and (state.has('2HORIZONTAL', player) or state.has('claw', player) and (state.has('2LEDGE', player) or state.has('LEDGE', player) and state.has('HORIZONTAL', player)) or state.has('FULLSILVA', player) or state.has('LEDGE', player) and state.has('sinner', player) or state.has('djump', player) and state.has('dash', player) and (state.has('silva', player) or state.has('dodge', player))))
    fn("Castle_10_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Castle10Right', player) or state.has('Castle10Bottom', player))
    fn("Castle_10_GAMEPLAY.BP_SCR_LV1M_2000_3", lambda state: state.has('MaelstromRemparts', player))
    fn("Castle_12_GAMEPLAY.BP_Interactable_Item_PassiveSlot_2", lambda state: state.has('Castle12Bottom', player) and state.has('hook', player))
    fn("Castle_12_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Castle12Bottom', player))
    fn("Castle_12_GAMEPLAY.BP_Interactable_Item_Tip4", lambda state: state.has('Castle12Bottom', player))
    fn("Castle_12_GAMEPLAY.BP_SCR_LV1M_2001_1", lambda state: state.has('Castle12Bottom', player) and (state.has('hook', player) or state.has('claw', player) or state.has('HORIZONTAL', player)))
    fn("Castle_13_GAMEPLAY.BP_Interactable_Item_MaxHPUp_02_2", lambda state: state.has('Castle13Bottom', player) and (state.has('silva', player) and state.has('djump', player) and state.has('claw', player) or (state.has('FULLSILVA', player) or state.has('3LEDGE', player)) and state.has('hook', player) or state.has('2LEDGE', player) and state.has('hook', player) and state.has('claw', player) or state.has('LEDGE', player) and state.has('HORIZONTAL', player) and state.has('claw', player) and state.has('hook', player)))
    fn("Castle_14_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('Castle14Left', player) and state.has('hook', player))
    fn("Castle_14_GAMEPLAY.BP_SCR_LV1L_2220_3", lambda state: state.has('Castle14Left', player) and state.has('CHARGE', player) and (state.has('claw', player) or state.has('LEDGE', player) and state.has('HORIZONTAL', player)))
    fn("Castle_14_GAMEPLAY.BP_SCR_LV2LL_0000_2", lambda state: state.has('Castle14Left', player) and (state.has('claw', player) and (state.has('3LEDGE', player) or state.has('FULLSILVA', player) or state.has('sinner', player) and state.has('2LEDGE', player) or state.has('silva', player) and state.has('2HORIZONTAL', player) or state.has('dodge', player) and state.has('dash', player) and state.has('2LEDGE', player))))
    fn("Castle_15_GAMEPLAY.BP_Interactable_Item_HealPower_Up_2", lambda state: state.has('TowerAlcove', player))
    fn("Castle_15_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Castle15Bottom', player) or state.has('Castle15Left', player))
    fn("Castle_16_GAMEPLAY.BP_e2032_BigKnight", lambda state: state.has('Castle16Right', player))
    fn("Castle_16_GAMEPLAY.BP_SCR_LV1M_2190_3", lambda state: state.has('Aegis', player))
    fn("Castle_16_GAMEPLAY.BP_SCR_LV1M_2190_4", lambda state: state.has('Aegis', player))
    fn("Castle_16_GAMEPLAY.BP_SCR_LV1M_2190_6", lambda state: state.has('Aegis', player))
    fn("Castle_16_GAMEPLAY.BP_SCR_LV1M_2190_7", lambda state: state.has('Aegis', player))
    fn("Castle_16_GAMEPLAY.BP_SCR_LV1M_2191_2", lambda state: state.has('Aegis', player))
    fn("Castle_16_GAMEPLAY.BP_SCR_LV1S_2100_3", lambda state: state.has('Aegis', player))
    fn("Castle_16_GAMEPLAY.BP_SCR_LV1S_2100_4", lambda state: state.has('Aegis', player))
    fn("Castle_16_GAMEPLAY.BP_SCR_LV1S_2100_6", lambda state: state.has('Aegis', player))
    fn("Castle_16_GAMEPLAY.BP_SCR_LV1S_2101_2", lambda state: state.has('Aegis', player))
    fn("Castle_16_GAMEPLAY.BP_SCR_LV1S_2101_4", lambda state: state.has('Aegis', player) and state.has('claw', player))
    fn("Castle_17_GAMEPLAY.BP_SCR_LV1M_2000_3", lambda state: state.has('Castle17Right', player) and (state.has('LEDGE', player) or state.has('claw', player)))
    fn("Castle_18_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('Castle18Right', player) and state.has('CHARGE', player))
    fn("Castle_18_GAMEPLAY.BP_Interactable_Item_Tip4", lambda state: state.has('Castle18Bottom', player) and (state.has('claw', player) or state.has('hook', player) and state.has('LEDGE', player)) and state.has('CHARGE', player))
    fn("Castle_18_GAMEPLAY.BP_Interactable_Passives_Treasure_2", lambda state: state.has('Castle18Bottom', player) and (state.has('claw', player) or state.has('hook', player) and state.has('LEDGE', player)) and state.has('CHARGE', player))
    fn("Castle_18_GAMEPLAY.BP_SCR_LV2L_2221_2", lambda state: state.has('Castle18Bottom', player) and state.has('hook', player) and state.has('LEDGE', player) and state.has('CHARGE', player))
    fn("Castle_19_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Castle19Right', player) or state.has('Castle19Left', player))
    fn("Castle_20_GAMEPLAY.BP_e5030_Leader", lambda state: state.has('Castle20Left', player))
    fn("Castle_21_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Castle21Left', player))
    fn("Castle_21_GAMEPLAY.BP_Interactable_Passives_Treasure_2", lambda state: state.has('Castle21Left', player))
    fn("Castle_21_GEO.BP_SCR_LV1L_2120_2", lambda state: state.has('Castle21Left', player))
    fn("Cave_01_GAMEPLAY.BP_Interactable_Passive_Parry_2", lambda state: state.has('Cave01Bottom', player) or state.has('Cave01Left', player))
    fn("Cave_01_GAMEPLAY.BP_SCR_LV2LL_0000_2", lambda state: state.has('Cave01Bottom', player) and (state.has('claw', player) or state.has('djump', player) or state.has('champion', player) or state.has('silva', player) and state.has('dodge', player)) or state.has('Cave01Left', player) and state.has('3LEDGE', player) and state.has('2HORIZONTAL', player))
    fn("Cave_02_GAMEPLAY.BP_SCR_LV1M_2160_1", lambda state: state.has('Cave02Right', player) and (state.has('hook', player) or state.has('claw', player) and (state.has('HORIZONTAL', player) or state.has('djump', player) or state.has('champion', player) and state.has('dash', player) or state.has('silva', player) and state.has('dash', player))))
    fn("Cave_02_GAMEPLAY.BP_SCR_LV1S_2020_2", lambda state: state.has('Cave02Right', player))
    fn("Cave_03_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Cave03Left', player) or state.has('Cave03Right', player) or state.has('Cave03Top', player))
    fn("Cave_03_GAMEPLAY.BP_Interactable_Item_Tip4", lambda state: state.has('Cave03Right', player))
    fn("Cave_04_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('Cave04Bottom', player))
    fn("Cave_05_GAMEPLAY.BP_SCR_LV1M_2161_2", lambda state: state.has('Cave05Bottom', player) and (state.has('hook', player) or state.has('LEDGE', player) or state.has('dash', player) or state.has('HORIZONTAL', player)))
    fn("Cave_06_GAMEPLAY.BP_Interactable_Item_Tip4", lambda state: state.has('Cave06Top', player))
    fn("Cave_06_GAMEPLAY.BP_Interactable_Item_Tip5", lambda state: state.has('Cave06Top', player))
    fn("Cave_06_GAMEPLAY.BP_Interactable_Passives_Treasure_2", lambda state: state.has('Cave06Top', player))
    fn("Cave_07_GAMEPLAY.BP_e2162_Spider", lambda state: state.has('Cave07Right', player) or state.has('Cave07Top', player))
    fn("Cave_07_GAMEPLAY.BP_SCR_LV1M_2161_2", lambda state: state.has('Spider', player) and state.has('swim', player))
    fn("Cave_08_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('Cave08Left', player) and state.has('slam', player))
    fn("Cave_09_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_Drop", lambda state: state.has('Cave09Top', player) and (state.has('claw', player) or state.has('LEDGE', player)))
    fn("Cave_09_GAMEPLAY.BP_Interactable_Item_PassiveSlot_Drop", lambda state: state.has('Cave09Top', player))
    fn("Cave_10_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_Drop", lambda state: state.has('Cave10Left', player))
    fn("Cave_10_GAMEPLAY.BP_SCR_LV1S_2011_2", lambda state: state.has('Cave10Bottom', player))
    fn("Cave_11_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Cave11Left', player) or state.has('Cave11Top', player) or state.has('Cave11Right1', player) or state.has('Cave11Right2', player))
    fn("Cave_11_GAMEPLAY.BP_SCR_LV1M_2161_2", lambda state: state.has('Cave11Left', player) and (state.has('LEDGE', player) or state.has('HORIZONTAL', player) or state.has('hook', player) or state.has('dash', player)))
    fn("Cave_11_GAMEPLAY.BP_SCR_LV2M_2050_2", lambda state: state.has('Cave11Tip', player) and state.has('swim', player))
    fn("Cave_12_GAMEPLAY.BP_Interactable_Item_FinalPassivePart_2", lambda state: state.has('Cave12Right', player))
    fn("Cave_13_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Cave13Top', player) or state.has('Cave13Left', player) or state.has('Cave13Right', player) or state.has('Cave13Bottom', player))
    fn("Cave_13_GAMEPLAY.BP_SCR_LV2L_2091_4", lambda state: state.has('Ossuary', player) and state.has('hook', player) or state.has('Cave13Bottom', player) and state.has('claw', player))
    fn("Cave_13_GAMEPLAY.BP_SCR_LV2M_2161_5", lambda state: state.has('Cave13Left', player) and (state.has('dash', player) or state.has('LEDGE', player) or state.has('HORIZONTAL', player)))
    fn("Cave_14_GAMEPLAY.BP_SCR_LV1S_2020_7", lambda state: state.has('Cave14Right', player))
    fn("Cave_15_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Cave15Right', player))
    fn("Cave_15_GAMEPLAY.BP_SCR_LV1L_2070_3", lambda state: state.has('Cave15Right', player) and state.has('slam', player))
    fn("Cave_15_GAMEPLAY.BP_SCR_LV1S_2020_2", lambda state: state.has('Cave15Right', player) or state.has('Cave15Left', player))
    fn("Cave_16_GAMEPLAY.BP_Interactable_Item_Tip4", lambda state: state.has('Cave16Right', player) or state.has('Cave16Bottom', player) or state.has('Cave16Left', player))
    fn("Cave_16_GAMEPLAY.BP_SCR_LV1L_2091_5", lambda state: state.has('GreatHall', player) and (state.has('hook', player) or state.has('claw', player) and (state.has('2LEDGE', player) or state.has('LEDGE', player) and state.has('HORIZONTAL', player))))
    fn("Cave_17_GAMEPLAY.BP_SCR_LV3M_5000_2", lambda state: state.has('Cave17Top', player) and state.has('swim', player))
    fn("Cave_18_GAMEPLAY.BP_Interactable_Passive_healpowerup_2", lambda state: state.has('Cave18Left1', player))
    fn("Cave_19_GAMEPLAY.BP_e2022_Soldier", lambda state: state.has('Cave19Top', player) or state.has('Cave19Left', player))
    fn("Cave_19_GAMEPLAY.BP_Interactable_Item_HealPower_Up_2", lambda state: state.has('Archer', player))
    fn("Cave_19_GAMEPLAY.BP_Interactable_Item_PassiveSlot_Drop", lambda state: state.has('Archer', player) and (state.has('hook', player) or state.has('LEDGE', player) or state.has('HORIZONTAL', player)))
    fn("Cave_20_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_Drop", lambda state: state.has('Cave20Top', player))
    fn("Cave_20_GAMEPLAY.BP_Interactable_Item_Tip4", lambda state: state.has('Cave20Top', player))
    fn("Cave_20_GAMEPLAY.BP_SCR_LV1S_2011_2", lambda state: state.has('Cave20Top', player))
    fn("Cave_21_GAMEPLAY.BP_Interactable_Passive_healcountup_2", lambda state: state.has('Cave21Right', player) or state.has('Cave21Left', player))
    fn("Cave_22_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Cave22Right', player))
    fn("Cave_23_GAMEPLAY.BP_e5021_OlderSister", lambda state: state.has('Cave23Right', player) or state.has('Cave23Left', player))
    fn("Cave_23_GAMEPLAY.BP_Interactable_Item_Tip4", lambda state: state.has('Silva', player))
    fn("Church_02_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_Drop", lambda state: state.has('Church02Right', player))
    fn("Church_02_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Church02Right', player))
    fn("Church_03_GAMEPLAY.BP_e5011_YoungerSister", lambda state: state.has('Church03Left', player))
    fn("Church_04_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Church04Right', player) or state.has('Church04Left', player))
    fn("Church_05_GAMEPLAY.BP_Interactable_Passive_MaxHPUp_Lv1_2", lambda state: state.has('Church05Top', player) or state.has('CathedralCloister', player) and state.has('LEDGE', player))
    fn("CathedralCloister", lambda state: state.has('Church05Right', player) or state.has('Church05Bottom', player) or state.has('Church05Top', player))
    fn("Church_07_GAMEPLAY.BP_e2012_Slime_Unique", lambda state: state.has('Church07Right', player))
    fn("Church_07_GAMEPLAY.BP_Interactable_Item_PassiveSlot_2", lambda state: state.has('Youth', player) and state.has('slam', player))
    fn("Church_08_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('Crossroads', player) and state.has('swim', player))
    fn("Church_08_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Church08Top', player) or state.has('Church08Bottom', player) or state.has('Church08Left', player))
    fn("Church_09_GAMEPLAY.BP_e2092_Priest", lambda state: state.has('Church09Bottom', player) or state.has('Church09Top', player))
    fn("Church_09_GAMEPLAY.BP_Interactable_Passive_JumpHeightUp_2", lambda state: state.has('Church09Bottom', player) and state.has('claw', player) and state.has('CHARGE', player))
    fn("Church_09_GAMEPLAY.BP_SCR_LV2M_2001_2", lambda state: state.has('Chief', player))
    fn("Church_10_GAMEPLAY.BP_Interactable_Item_Tip_2", lambda state: state.has('Church10Left', player) or state.has('Church10Right', player))
    fn("Church_10_GAMEPLAY.BP_Interactable_Item_Tip2", lambda state: state.has('Cellar', player))
    fn("Church_11_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('Church11Left', player))
    fn("Church_11_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Church11Top', player))
    fn("Church_12_GAMEPLAY.BP_Interactable_Item_Tip1", lambda state: state.has('Church12Right', player))
    fn("Church_13_GAMEPLAY.BP_Interactable_Item_Tip4", lambda state: state.has('Church13Top', player))
    fn("Church_14_GAMEPLAY.BP_Interactable_Item_HealPower_Up_2", lambda state: state.has('Church14Bottom', player))
    fn("Church_14_GAMEPLAY.BP_Interactable_Item_Tip5", lambda state: state.has('Church14Bottom', player))
    fn("Forest_02_GAMEPLAY.BP_SCR_LV1S_2130_2", lambda state: state.has('Forest02Left', player) or state.has('Forest02Right2', player) and state.has('hook', player))
    fn("Forest_03_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('Forest03Left', player) and state.has('swim', player))
    fn("Forest_03_GAMEPLAY.BP_Interactable_Item_PassiveSlot_2", lambda state: state.has('Forest03Left', player) and state.has('swim', player))
    fn("Forest_04_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_Drop", lambda state: state.has('Forest04Right', player))
    fn("Forest_04_GAMEPLAY.BP_Interactable_Passive_dmgup_swimming_2", lambda state: state.has('Forest04Left', player) and (state.has('LEDGE', player) or state.has('claw', player) and state.has('HORIZONTAL', player)))
    fn("Forest_04_GAMEPLAY.BP_SCR_LV1S_2100_2", lambda state: state.has('Forest04Left', player) and (state.has('slam', player) and state.has('LEDGE', player)))
    fn("Forest_05_GAMEPLAY.BP_Interactable_Item_Tip4", lambda state: state.has('Forest05Right', player) or state.has('Forest05Left', player) or state.has('Forest05Top', player))
    fn("Forest_06_GAMEPLAY.BP_e2122_Fungus", lambda state: state.has('Forest06Bottom', player) and state.has('LEDGE', player))
    fn("Forest_06_GAMEPLAY.BP_Interactable_Item_Tip4", lambda state: state.has('Forest06Bottom', player) and state.has('LEDGE', player))
    fn("Forest_06_GAMEPLAY.BP_SCR_LV2M_2120_3", lambda state: state.has('Forest06Bottom', player) and (state.has('hook', player) or state.has('LEDGE', player) and state.has('slam', player) or state.has('2LEDGE', player) or state.has('LEDGE', player) and state.has('HORIZONTAL', player)))
    fn("Forest_07_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_Drop", lambda state: (state.has('Forest07Left', player) or state.has('Forest07Bottom', player)) and (state.has('LEDGE', player) or state.has('hook', player) or state.has('HORIZONTAL', player) or state.has('claw', player)))
    fn("Forest_07_GAMEPLAY.BP_SCR_LV1S_2121_1", lambda state: state.has('Forest07Right', player) and (state.has('hook', player) or state.has('claw', player) and state.has('LEDGE', player)))
    fn("Forest_07_GAMEPLAY.BP_SCR_LV1S_2130_2", lambda state: state.has('Forest07Left', player) or state.has('Forest07Right', player))
    fn("Forest_08_GAMEPLAY.BP_Interactable_Passive_Treasure_2", lambda state: state.has('Forest08Top', player) and (state.has('LEDGE', player) or state.has('hook', player) or state.has('claw', player) and state.has('HORIZONTAL', player)))
    fn("Forest_08_GAMEPLAY.BP_Interactable_Passive_Treasure2", lambda state: state.has('ManisasRing', player) and (state.has('2LEDGE', player) or state.has('LEDGE', player) and state.has('HORIZONTAL', player) or state.has('claw', player) and state.has('sinner', player) or state.has('hook', player)))
    fn("Forest_08_GAMEPLAY.BP_SCR_LV2M_2120_1", lambda state: state.has('Forest08Top', player) and (state.has('LEDGE', player) or state.has('HORIZONTAL', player) or state.has('dash', player)))
    fn("Forest_09_GAMEPLAY.BP_Interactable_Item_HealPower_Up_2", lambda state: state.has('Forest10Left', player) and state.has('swim', player) and (state.has('LEDGE', player) or state.has('claw', player)))
    fn("Forest_09_GAMEPLAY.BP_Interactable_Item_Tip1", lambda state: state.has('Forest10Left', player) and state.has('swim', player) and (state.has('LEDGE', player) or state.has('claw', player)))
    fn("Forest_09_GAMEPLAY.BP_SCR_LV2S_2130_2", lambda state: (state.has('Forest09Top', player) or state.has('Forest09Left', player)) and state.has('swim', player))
    fn("Forest_10_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Forest10Bottom2', player) or state.has('Forest10Bottom1', player) or state.has('Forest10Left', player) or state.has('Forest10Right', player))
    fn("Forest_11_GAMEPLAY.BP_e2132_Mandrake", lambda state: state.has('Forest11Top', player))
    fn("Forest_11_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('Forest11Top', player))
    fn("Forest_11_GAMEPLAY.BP_Interactable_Item_PassiveSlot_Drop", lambda state: state.has('Forest11Top', player))
    fn("Forest_11_GAMEPLAY.BP_Interactable_Passives_Treasure_2", lambda state: state.has('Forest11Right', player) and (state.has('LEDGE', player) or state.has('HORIZONTAL', player) or state.has('dash', player)))
    fn("Forest_11_GAMEPLAY.BP_SCR_LV1M_2120_2", lambda state: state.has('Forest11Right', player) and (state.has('LEDGE', player) and state.has('claw', player) or state.has('hook', player) or state.has('2HORIZONTAL', player) and (state.has('dash', player) or state.has('djump', player) or state.has('silva', player))))
    fn("Forest_11_GAMEPLAY.BP_SCR_LV1S_2130_2", lambda state: state.has('Forest11Right', player) and state.has('swim', player))
    fn("Forest_12_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_Drop", lambda state: state.has('Forest12Left', player) and (state.has('LEDGE', player) or state.has('claw', player) or state.has('hook', player)))
    fn("Forest_12_GAMEPLAY.BP_SCR_LV1M_2131_3", lambda state: state.has('Forest12Bottom', player) or state.has('Forest12Right', player))
    fn("Forest_13_GAMEPLAY.BP_SCR_LV1S_2130_3", lambda state: state.has('Forest13Top', player))
    fn("Forest_14_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Forest14Bottom', player) or state.has('Forest14Top', player) or state.has('Forest14Left', player))
    fn("Forest_15_GAMEPLAY.BP_e5040_Witch", lambda state: state.has('Forest_15_GAMEPLAY', player)state.has('BP_WorldTravelVolume_2', player))
    fn("Forest_16_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Forest16Left', player))
    fn("Forest_16_GAMEPLAY.BP_Interactable_Passives_Treasure_2", lambda state: state.has('Forest16Left', player))
    fn("Forest_16_GAMEPLAY.BP_SCR_LV1LL_0000_2", lambda state: state.has('Forest16Left', player))
    fn("Forest_17_GAMEPLAY.BP_Interactable_Item_MaxHPUp_02_Treasure_2", lambda state: state.has('Forest17Left', player) and (state.has('claw', player) or state.has('LEDGE', player)))
    fn("Forest_17_GAMEPLAY.BP_Interactable_Item_Tip4", lambda state: state.has('Forest17Left', player) and (state.has('claw', player) or state.has('LEDGE', player) and state.has('hook', player) or state.has('silva', player) and state.has('djump', player)))
    fn("Forest_17_GAMEPLAY.BP_Interactable_Passives_Treasure_2", lambda state: state.has('Forest17Left', player) and (state.has('claw', player) or state.has('LEDGE', player)))
    fn("Forest_17_Map.BP_Interactable_Item_Tip5", lambda state: state.has('Forest17Left', player))
    fn("Fort_01_GAMEPLAY.BP_e2192_Gargoyle", lambda state: state.has('Fort01Left1', player) or state.has('Fort01Right', player) and (state.has('LEDGE', player) or state.has('hook', player)))
    fn("Fort_01_GAMEPLAY.BP_SCR_LV1M_2190_2", lambda state: state.has('Fort01Left1', player))
    fn("Fort_02_GAMEPLAY.BP_SCR_LV1S_2021_2", lambda state: state.has('Fort02Left', player))
    fn("Fort_02_GAMEPLAY.BP_SCR_LV2S_2021_2", lambda state: state.has('Fort02Right', player))
    fn("Fort_03_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Fort03Right', player) or state.has('Fort03Left1', player) or state.has('Fort03Left2', player) or state.has('Fort03Top', player))
    fn("Fort_04_GAMEPLAY.BP_SCR_LV1L_2230_8", lambda state: state.has('Fort04Left', player) and (state.has('CHARGE', player) and (state.has('LEDGE', player) or state.has('claw', player) or state.has('HORIZONTAL', player))))
    fn("Fort_05_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_Drop", lambda state: state.has('Fort05Right', player) and state.has('LEDGE', player))
    fn("Fort_05_GAMEPLAY.BP_Interactable_Item_PassiveSlot_Drop", lambda state: state.has('Fort05Bottom2', player) and (state.has('LEDGE', player) and (state.has('hook', player) or state.has('claw', player))))
    fn("Fort_05_GAMEPLAY.BP_SCR_LV1S_2020_6", lambda state: state.has('Fort05Bottom2', player) and state.has('LEDGE', player) and state.has('slam', player) or state.has('Fort05Bottom1', player))
    fn("Fort_06_GAMEPLAY.BP_SCR_LV1M_2190_4", lambda state: state.has('Fort06Right', player) and (state.has('LEDGE', player) and state.has('claw', player)))
    fn("Fort_07_GAMEPLAY.BP_SCR_LV1S_2021_1", lambda state: state.has('Fort07Bottom1', player) and (state.has('LEDGE', player) or state.has('claw', player)))
    fn("Fort_08_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Fort08Left', player))
    fn("Fort_09_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Fort09Left', player))
    fn("Fort_09_GAMEPLAY.BP_Interactable_Passive_dmgcut_Lv3_2", lambda state: state.has('Fort09Left', player) and state.has('CHARGE', player))
    fn("Fort_09_GAMEPLAY.BP_SCR_LV1S_2020_2", lambda state: state.has('Fort09Top1', player))
    fn("Fort_09_GAMEPLAY.BP_SCR_LV2M_2190_3", lambda state: state.has('Fort09Top2', player))
    fn("Fort_10_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('Courtyard', player) and state.has('claw', player) and state.has('LEDGE', player))
    fn("Fort_10_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Fort10Right', player) or state.has('Fort10Top', player))
    fn("Fort_11_GAMEPLAY.BP_Interactable_Passives_Treasure_2", lambda state: state.has('slam', player) and state.has('swim', player) and (state.has('Fort11Stagnant', player) or state.has('Fort11Bottom', player) and (state.has('LEDGE', player) and (state.has('sinner', player) or state.has('dodge', player) and state.has('claw', player)) or state.has('2LEDGE', player))))
    fn("Fort_11_GAMEPLAY.BP_SCR_LV1M_2190_4", lambda state: state.has('Fort11Top2', player) or state.has('Fort11Bottom', player) and (state.has('LEDGE', player) and (state.has('sinner', player) or state.has('dodge', player) and state.has('claw', player)) or state.has('2LEDGE', player)) and (state.has('hook', player) or state.has('2LEDGE', player) and state.has('claw', player) or state.has('3LEDGE', player)))
    fn("Fort_12_GAMEPLAY.BP_e2232_Dragon", lambda state: state.has('Fort12HP', player) and state.has('CHARGE', player))
    fn("Fort_12_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_7", lambda state: state.has('Fort12Top', player) or state.has('Fort12Right', player) and (state.has('claw', player) and (state.has('LEDGE', player) and state.has('HORIZONTAL', player) or state.has('2LEDGE', player)) or state.has('3LEDGE', player)))
    fn("Fort_13_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('Fort13Left', player))
    fn("Fort_13_GAMEPLAY.BP_Interactable_Item_PassiveSlot_Drop", lambda state: state.has('Fort13Bottom1', player) and state.has('claw', player) and state.has('LEDGE', player) or state.has('Fort13Top', player))
    fn("Fort_14_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Fort14Right', player) and state.has('hook', player) and state.has('slam', player) and state.has('unlock', player) and state.has('swim', player))
    fn("Fort_14_GAMEPLAY.BP_Interactable_Passives_Treasure_2", lambda state: state.has('Fort14Right', player) and state.has('hook', player) and state.has('slam', player) and state.has('unlock', player) and state.has('swim', player))
    fn("Fort_14_GAMEPLAY.BP_SCR_LV1L_2231_2", lambda state: state.has('Fort14Bottom', player) and state.has('CHARGE', player))
    fn("Fort_14_GAMEPLAY.BP_SCR_LV1LL_0000_2", lambda state: state.has('Fort14Right', player) and state.has('hook', player) and state.has('slam', player) and state.has('unlock', player) and state.has('swim', player))
    fn("Fort_14_GAMEPLAY.BP_SCR_LV2S_2020_3", lambda state: state.has('Fort14Right', player) or state.has('Fort14Left', player) or state.has('Fort14Bottom', player))
    fn("Fort_15_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Fort15Right2', player))
    fn("Fort_15_GAMEPLAY.BP_Interactable_Passives_Treasure_2", lambda state: state.has('Fort15Top', player) and (state.has('hook', player) or state.has('2LEDGE', player)))
    fn("Fort_15_GAMEPLAY.BP_SCR_LV1M_2190_2", lambda state: state.has('Fort15Right2', player) and state.has('claw', player) or state.has('Fort15Top', player) or state.has('Fort15Bottom', player))
    fn("Fort_15_GAMEPLAY.BP_SCR_LV1S_2021_1", lambda state: state.has('Fort15Right2', player) and state.has('LEDGE', player))
    fn("Fort_16_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Fort16Left1', player) or state.has('Fort16Top', player) or state.has('Fort16Left2', player) or state.has('Fort16Right', player))
    fn("Fort_17_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('Fort17Bottom', player))
    fn("Fort_18_GAMEPLAY.BP_Interactable_Item_MaxHPUp_02_Treasure_2", lambda state: state.has('Fort18Right', player) and (state.has('claw', player) and (state.has('sinner', player) or state.has('dodge', player) and state.has('LEDGE', player) or state.has('2LEDGE', player) or state.has('djump', player) and state.has('dash', player))))
    fn("Fort_18_GAMEPLAY.BP_Interactable_Item_PassiveSlot_Drop", lambda state: state.has('Fort18Bottom', player) and (state.has('LEDGE', player) or state.has('claw', player)))
    fn("Fort_19_GAMEPLAY.BP_Interactable_Passives_Treasure_2", lambda state: state.has('Fort19Top', player))
    fn("Fort_19_GAMEPLAY.BP_SCR_LV2M_2190_4", lambda state: state.has('Fort19Top', player) and state.has('claw', player))
    fn("Fort_19_GAMEPLAY.BP_SCR_LV2S_2021_2", lambda state: state.has('Fort19Left', player) and state.has('slam', player))
    fn("MourningHall", lambda state: state.has('Fort20Bottom', player) or state.has('Fort20Top', player))
    fn("Fort_21_GAMEPLAY.BP_e5070_Killer", lambda state: state.has('Fort21Bottom', player))
    fn("Fort_21_GAMEPLAY.BP_Interactable_Item_HealPower_Up_2", lambda state: state.has('Ulv', player) and (state.has('claw', player) or (state.has('silva', player) and state.has('djump', player) and (state.has('champion', player) or state.has('dodge', player)))))
    fn("Fort_21_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Ulv', player) and (state.has('claw', player) or (state.has('silva', player) and state.has('djump', player) and (state.has('champion', player) or state.has('dodge', player)))))
    fn("Oubliette_01_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_5", lambda state: state.has('Oubliette01Left', player) and state.has('swim', player))
    fn("Oubliette_01_GAMEPLAY.BP_SCR_LV1S_2010_3", lambda state: state.has('Oubliette01Left', player) and state.has('swim', player))
    fn("Oubliette_02_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Oubliette02Left', player) or state.has('Oubliette02Right1', player) or state.has('Oubliette02Right2', player))
    fn("Oubliette_03_GAMEPLAY.BP_SCR_LV1M_2050_2", lambda state: state.has('Oubliette03Left', player) and state.has('swim', player))
    fn("Oubliette_03_GAMEPLAY.BP_SCR_LV1S_2081_2", lambda state: state.has('Oubliette03Left', player) and state.has('swim', player))
    fn("Oubliette_03_GEO.BP_SCR_LV1LL_0000_2", lambda state: state.has('Oubliette03Right', player) and state.has('CHARGE', player))
    fn("Oubliette_04_GAMEPLAY.BP_SCR_LV1S_2020_2", lambda state: state.has('Oubliette04Left', player) and (state.has('FULLSILVA', player) or state.has('hook', player) or state.has('3LEDGE', player) or state.has('sinner', player) and state.has('silva', player) and state.has('djump', player) or state.has('silva', player) and state.has('champion', player) and state.has('dodge', player) or state.has('2HORIZONTAL', player) and state.has('dash', player) and state.has('LEDGE', player) or state.has('djump', player) and state.has('champion', player) and state.has('HORIZONTAL', player)))
    fn("Oubliette_04_GAMEPLAY.BP_SCR_LV2S_2010_3", lambda state: state.has('Oubliette04Right', player) or state.has('Oubliette04Left', player))
    fn("Oubliette_05_1_GAMEPLAY.BP_SCR_LV2S_2021_2", lambda state: state.has('Oubliette051Bottom', player))
    fn("Oubliette_05_2_GAMEPLAY.BP_SCR_LV1S_2010_3", lambda state: state.has('Oubliette052Bottom1', player) and (state.has('LEDGE', player) and state.has('claw', player) and state.has('hook', player)))
    fn("Oubliette_05_3_GAMEPLAY.BP_Interactable_Item_PassiveSlot_Drop", lambda state: state.has('Oubliette053Top', player))
    fn("Oubliette_05_GAMEPLAY.BP_Interactable_Item_MaxHPUp_02_2", lambda state: state.has('Oubliette05Top4', player))
    fn("Oubliette_05_GAMEPLAY.BP_SCR_LV1L_2220_3", lambda state: state.has('Oubliette05Top1', player) and state.has('CHARGE', player))
    fn("Oubliette_05_GAMEPLAY.BP_SCR_LV1S_2021_2", lambda state: state.has('Oubliette05Top4', player))
    fn("Oubliette_06_1_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Oubliette061Left', player))
    fn("Oubliette_06_2_GAMEPLAY.BP_Interactable_Passive_dmgup_maxHP_2", lambda state: state.has('Oubliette062Bottom2', player) and state.has('swim', player))
    fn("Oubliette_06_3_GAMEPLAY.BP_Interactable_Item_PassiveSlot_2", lambda state: state.has('Oubliette063Left1', player))
    fn("Oubliette_06_4_GAMEPLAY.BP_Interactable_Item_FinalPassivePart_2", lambda state: state.has('Oubliette064Top', player))
    fn("Oubliette_06_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_Drop", lambda state: state.has('Oubliette06Bottom', player))
    fn("Oubliette_06_GAMEPLAY.BP_Interactable_Item_PassiveSlot_2", lambda state: state.has('Oubliette06Bottom', player) and state.has('hook', player))
    fn("Oubliette_06_GAMEPLAY.BP_SCR_LV1S_2021_2", lambda state: state.has('Oubliette06Bottom', player))
    fn("Oubliette_07_1_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Oubliette071Top', player))
    fn("Oubliette_07_2_GAMEPLAY.BP_e2072_Mimic", lambda state: state.has('Oubliette072Bottom', player))
    fn("Oubliette_08_GAMEPLAY.BP_SCR_LV2M_2050_3", lambda state: state.has('slam', player) and (state.has('Oubliette08Top', player) or state.has('Oubliette08Right', player) and (state.has('hook', player) or state.has('LEDGE', player) or state.has('HORIZONTAL', player))))
    fn("Oubliette_08_GAMEPLAY.BP_SCR_LV2S_2081_2", lambda state: state.has('Oubliette08Left', player) and state.has('hook', player))
    fn("Oubliette_09_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('Oubliette09Top', player) and state.has('claw', player))
    fn("Oubliette_09_GAMEPLAY.BP_Interactable_Item_MaxHPUp_5", lambda state: state.has('Oubliette09Top', player) and state.has('claw', player))
    fn("Oubliette_09_GAMEPLAY.BP_SCR_LV1M_2050_2", lambda state: state.has('Oubliette09Top', player) and state.has('swim', player))
    fn("Oubliette_10_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Oubliette10Left1', player) or state.has('Oubliette10Right', player) or state.has('Oubliette10Left2', player) or state.has('Oubliette10Top', player))
    fn("Oubliette_11_GAMEPLAY.BP_SCR_LV2S_2020_2", lambda state: state.has('Oubliette11Left1', player) and (state.has('LEDGE', player) or state.has('dash', player) or state.has('HORIZONTAL', player) or state.has('hook', player)) or state.has('Oubliette11Left2', player) and state.has('hook', player))
    fn("Oubliette_12_GAMEPLAY.BP_e2182_Shadow", lambda state: state.has('Oubliette12Left', player))
    fn("Oubliette_13_1_GAMEPLAY.BP_Interactable_Passives_Treasure_2", lambda state: state.has('Oubliette131Bottom', player))
    fn("Oubliette_13_2_GAMEPLAY.BP_SCR_LV3S_5000_1", lambda state: state.has('Oubliette132Top', player))
    fn("Oubliette_13_GAMEPLAY.BP_Interactable_Item_PassiveSlot_2", lambda state: state.has('Oubliette13Right', player) and (state.has('claw', player) and state.has('LEDGE', player) or state.has('2LEDGE', player) or state.has('hook', player)))
    fn("Oubliette_13_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Oubliette13Left', player))
    fn("Oubliette_13_GAMEPLAY.BP_SCR_LV1M_2001_3", lambda state: state.has('Oubliette13Left', player))
    fn("Oubliette_13_GAMEPLAY.BP_SCR_LV1M_2180_2", lambda state: state.has('Oubliette13Left', player) and state.has('CHARGE', player) and (state.has('LEDGE', player) or state.has('HORIZONTAL', player) or state.has('hook', player) or state.has('dash', player) or state.has('claw', player)))
    fn("Oubliette_14_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Oubliette14Left', player) or state.has('Oubliette14Right', player))
    fn("Oubliette_15_GAMEPLAY.BP_e5060_Assassin", lambda state: state.has('Oubliette15Left', player) or state.has('Oubliette15Right', player))
    fn("Oubliette_16_GAMEPLAY.BP_Interactable_Item_HealPower_Up_2", lambda state: state.has('Oubliette16Right', player))
    fn("Oubliette_16_GAMEPLAY.BP_SCR_LV1L_2180_3", lambda state: state.has('Oubliette16Left', player))
    fn("Outside_03_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Outside03Right', player) and (state.has('claw', player) and (state.has('2LEDGE', player) or state.has('LEDGE', player) and state.has('HORIZONTAL', player) or state.has('champion', player))))
    fn("Outside_03_GAMEPLAY.BP_Interactable_Item_Tip4", lambda state: state.has('Grotto', player))
    fn("Outside_03_GAMEPLAY.BP_Interactable_Passive_ShortHeal_2", lambda state: state.has('Outside03Right', player) and state.has('swim', player))
    fn("Outside_03_GAMEPLAY.BP_SCR_LV2L_2230_2", lambda state: state.has('Grotto', player))
    fn("Swamp_04_GAMEPLAY.BP_e2172_Inferior", lambda state: state.has('Swamp04Bottom', player) and state.has('unlock', player))
    fn("Swamp_04_GAMEPLAY.BP_Interactable_Item_PassiveSlot_2", lambda state: state.has('Swamp04Left', player))
    fn("Swamp_05_GAMEPLAY.BP_SCR_LV2M_2171_2", lambda state: state.has('Swamp05Left', player) and state.has('swim', player))
    fn("Swamp_05_GEO.BP_SCR_LV1M_2051_2", lambda state: state.has('Swamp05Left', player) and state.has('swim', player))
    fn("Swamp_06_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Swamp06Left', player) or state.has('Swamp06Top', player))
    fn("Swamp_06_GAMEPLAY.BP_Interactable_Passives_Treasure_2", lambda state: state.has('Swamp06Top', player))
    fn("Swamp_06_GAMEPLAY.BP_SCR_LV1L_2180_3", lambda state: state.has('Swamp06Top', player))
    fn("Swamp_07_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('Swamp07Right', player) and state.has('claw', player))
    fn("Swamp_07_GAMEPLAY.BP_Interactable_Passive_RecastTimeCut_Lv2_2", lambda state: state.has('Swamp07Left', player) and (state.has('claw', player) and state.has('LEDGE', player)))
    fn("Swamp_08_GAMEPLAY.BP_Interactable_Item_MaxHPUp_02_2", lambda state: state.has('Swamp08Right2', player) and state.has('swim', player))
    fn("Swamp_08_GAMEPLAY.BP_SCR_LV1M_2051_2", lambda state: state.has('Swamp08Right2', player) and state.has('swim', player))
    fn("Swamp_08_GAMEPLAY.BP_SCR_LV2M_2051_2", lambda state: state.has('Swamp08Right2', player) and state.has('swim', player))
    fn("Swamp_09_GAMEPLAY.BP_Interactable_Passives_Treasure_2", lambda state: state.has('Swamp09Right2', player) and (state.has('LEDGE', player) or state.has('HORIZONTAL', player)))
    fn("Swamp_09_GAMEPLAY.BP_SCR_LV2M_2170_2", lambda state: state.has('Swamp09Right1', player) and (state.has('LEDGE', player) and state.has('HORIZONTAL', player) or state.has('2LEDGE', player)))
    fn("Swamp_1_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Swamp1Bottom', player) or state.has('Swamp1Left', player))
    fn("Swamp_10_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Swamp10Right', player))
    fn("Swamp_10_GAMEPLAY.BP_SCR_LV1M_2051_2", lambda state: state.has('Lab3', player) and state.has('swim', player))
    fn("Swamp_11_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('Swamp11Left', player) and (state.has('LEDGE', player) and state.has('HORIZONTAL', player) or state.has('2HORIZONTAL', player) or state.has('silva', player) and state.has('djump', player)))
    fn("Swamp_11_GAMEPLAY.BP_Interactable_Passives_Treasure_2", lambda state: state.has('Swamp11Left', player))
    fn("Swamp_12_GAMEPLAY.BP_Interactable_Item_HealPower_Up_2", lambda state: state.has('Lab4', player) and state.has('slam', player))
    fn("Swamp_12_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Swamp12Left', player) or state.has('Swamp12Bottom', player) or state.has('Swamp12TP', player))
    fn("Swamp_13_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('Swamp13Top2', player))
    fn("Swamp_13_GAMEPLAY.BP_SCR_LV1L_2170_3", lambda state: state.has('Swamp13Top1', player) and state.has('slam', player) or state.has('Swamp13Top2', player) and state.has('CHARGE', player) and state.has('slam', player))
    fn("Swamp_13_GAMEPLAY.BP_SCR_LV2L_2170_3", lambda state: state.has('Swamp13Bottom', player) and (state.has('hook', player) or state.has('claw', player)))
    fn("Swamp_14_GAMEPLAY.BP_Interactable_Item_PassiveSlot_2", lambda state: state.has('Swamp14Top', player) or state.has('Swamp14Bottom', player) and (state.has('LEDGE', player) or state.has('claw', player) or state.has('hook', player)))
    fn("Swamp_14_GAMEPLAY.BP_SCR_LV1L_2170_3", lambda state: state.has('Swamp14Top', player) and (state.has('2LEDGE', player) or state.has('hook', player)))
    fn("Swamp_15_GAMEPLAY.BP_e2052_Toad", lambda state: state.has('Swamp15Left', player) and state.has('swim', player) and state.has('mask', player))
    fn("Swamp_15_GAMEPLAY.BP_SCR_LV1M_2171_2", lambda state: state.has('Swamp15Top', player))
    fn("Swamp_16_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Swamp16Top', player) or state.has('Swamp16Left', player))
    fn("Swamp_18_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('Faden', player))
    fn("Swamp_18_GAMEPLAY.BP_Interactable_Item_Tip4", lambda state: state.has('Faden', player))
    fn("Swamp_18_GAMEPLAY.BP_Interactable_Spirit_s5080_2", lambda state: state.has('Swamp18Right', player))
    fn("Swamp_18_GAMEPLAY.BP_SCR_LV1LL_miliel_2", lambda state: state.has('Faden', player) and (state.has('claw', player) and (state.has('LEDGE', player) and state.has('2HORIZONTAL', player)) or (state.has('2LEDGE', player) and state.has('dodge', player))))
    fn("Swamp_2_GAMEPLAY.BP_SCR_LV2S_2010_2", lambda state: state.has('Swamp2Top', player))
    fn("Swamp_2_GAMEPLAY.BP_SCR_LV2S_2121_1", lambda state: state.has('Swamp2Top', player) and (state.has('claw', player) or state.has('LEDGE', player) and state.has('hook', player)))
    fn("Swamp_3_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_Drop", lambda state: state.has('Swamp3Top', player) and state.has('LEDGE', player))
    fn("Swamp_3_GAMEPLAY.BP_SCR_LV1L_2170_3", lambda state: state.has('Swamp3Top', player))
    fn("Village_02_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_Drop", lambda state: state.has('Village02Left', player))
    fn("Village_02_GAMEPLAY.BP_SCR_LV1S_2020_2", lambda state: state.has('Village02Left', player) and (state.has('djump', player) and (state.has('silva', player) or state.has('champion', player)) or (state.has('djump', player) or state.has('silva', player)) and state.has('HORIZONTAL', player) or state.has('hook', player)))
    fn("Village_02_GAMEPLAY.BP_SCR_LV1S_2100_2", lambda state: state.has('Village02Left', player) and (state.has('2LEDGE', player) or state.has('silva', player) and state.has('dodge', player) or state.has('hook', player) and (state.has('LEDGE', player) or state.has('claw', player))))
    fn("Village_03_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('slam', player) and (state.has('Village03Right', player) and (state.has('LEDGE', player) or state.has('HORIZONTAL', player)) or state.has('Village03Bottom1', player) and (state.has('LEDGE', player) or state.has('claw', player))))
    fn("Village_03_GAMEPLAY.BP_Interactable_Passives_Treasure_2", lambda state: state.has('Village03Right', player) and (state.has('claw', player) or state.has('hook', player) or state.has('LEDGE', player) or state.has('HORIZONTAL', player) or state.has('dash', player)))
    fn("Village_03_GAMEPLAY.BP_SCR_LV1S_2021_2", lambda state: state.has('Village03Right', player) and (state.has('LEDGE', player) or state.has('HORIZONTAL', player)) or state.has('Village03Bottom1', player) and (state.has('LEDGE', player) or state.has('claw', player)))
    fn("Village_03_GAMEPLAY.BP_SCR_LV2S_2020_2", lambda state: state.has('slam', player) and (state.has('Village03Right', player) and (state.has('LEDGE', player) or state.has('HORIZONTAL', player)) or state.has('Village03Bottom1', player) and (state.has('LEDGE', player) or state.has('claw', player))))
    fn("Village_04_1_GAMEPLAY.BP_e2102_Crow", lambda state: state.has('Village041Bottom', player))
    fn("Village_04_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('Village04Top', player))
    fn("Village_04_GAMEPLAY.BP_Interactable_Passives_Treasure_2", lambda state: state.has('Village04Right', player) and (state.has('hook', player) and (state.has('LEDGE', player) or state.has('claw', player)) or state.has('LEDGE', player) and state.has('HORIZONTAL', player) or state.has('2LEDGE', player) or state.has('LEDGE', player) and state.has('claw', player)))
    fn("Village_04_GAMEPLAY.BP_SCR_LV1S_2010_1", lambda state: state.has('Village04Top', player))
    fn("Village_05_GAMEPLAY.BP_Interactable_Item_Tip4", lambda state: state.has('Village05Top', player) or state.has('Village05Left', player) or state.has('Village05Right', player))
    fn("Village_06_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('Village06Left', player))
    fn("Village_06_GAMEPLAY.BP_SCR_LV1M_2000_3", lambda state: state.has('Village06Right2', player) and (state.has('2LEDGE', player) or state.has('LEDGE', player) and state.has('claw', player) or (state.has('silva', player) or state.has('djump', player)) and state.has('HORIZONTAL', player) or state.has('champion', player) and state.has('sinner', player)))
    fn("Village_06_GAMEPLAY.BP_SCR_LV1S_2020_2", lambda state: state.has('Village06Left', player) and state.has('slam', player) and (state.has('2LEDGE', player) or state.has('LEDGE', player) and state.has('claw', player) or state.has('hook', player)))
    fn("Village_06_GAMEPLAY.BP_SCR_LV1S_2021_2", lambda state: state.has('Village06Left', player) and state.has('slam', player) and (state.has('2LEDGE', player) or state.has('LEDGE', player) and state.has('claw', player) or state.has('hook', player)))
    fn("Village_06_GAMEPLAY.BP_SCR_LV2S_2010_3", lambda state: state.has('Village06Left', player) and (state.has('LEDGE', player) or state.has('hook', player)))
    fn("Village_06_GAMEPLAY.BP_SCR_LV2S_2021_2", lambda state: state.has('Village06Left', player) and state.has('slam', player) and (state.has('LEDGE', player) or state.has('hook', player)))
    fn("Village_07_GAMEPLAY.BP_Interactable_Item_PassiveSlot_2", lambda state: state.has('Village07Left', player))
    fn("Village_07_GAMEPLAY.BP_SCR_LV1S_2100_3", lambda state: state.has('Village07Left', player))
    fn("Village_07_GAMEPLAY.BP_SCR_LV2S_2080_3", lambda state: state.has('Village07Left', player) and (state.has('hook', player) or state.has('2LEDGE', player)))
    fn("Village_08_GAMEPLAY.BP_e2002_Knight", lambda state: state.has('Village08Left', player))
    fn("Village_08_GAMEPLAY.BP_Interactable_Item_MaxHPUp_01_2", lambda state: state.has('Village08Left', player))
    fn("Village_08_GAMEPLAY.BP_SCR_LV1S_2021_2", lambda state: state.has('Village08Left', player) and state.has('swim', player))
    fn("Village_09_GAMEPLAY.BP_Interactable_Item_Tip3", lambda state: state.has('BridgeHead', player))
    fn("Village_09_GAMEPLAY.BP_Interactable_Item_Tip4", lambda state: state.has('Village09Right1', player) or state.has('Village09Right2', player) or state.has('Village09Left1', player) or state.has('Village09Left2', player))
    fn("Village_10_GAMEPLAY.BP_e5050_Giant", lambda state: state.has('Village10Left', player) or state.has('Village10Right', player))
    fn("Village_11_1_GAMEPLAY.BP_Interactable_Item_HealPower_Up_5", lambda state: state.has('Village111Bottom', player) and state.has('slam', player))
    fn("Village_11_GAMEPLAY.BP_Interactable_Item_Tip1", lambda state: state.has('Village11Left', player))
    fn("Village_11_GAMEPLAY.BP_Interactable_Item_Tip4", lambda state: state.has('Village11Left', player))
    fn("Village_11_GAMEPLAY.BP_SCR_LV2S_2020_3", lambda state: state.has('Village11Left', player))
    fn("Village_12_GAMEPLAY.BP_SCR_LV1S_2021_2", lambda state: state.has('Village12Left1', player))
    fn("Village_13_GAMEPLAY.BP_Interactable_Item_MaxHPUp_02_Treasure_2", lambda state: state.has('Village13Right', player) and (state.has('djump', player) or state.has('2LEDGE', player) or state.has('LEDGE', player) and state.has('HORIZONTAL', player)))
    fn("Village_13_GAMEPLAY.BP_Interactable_Item_PassiveSlot_Drop", lambda state: state.has('Village13Right', player))
    fn("Village_13_GAMEPLAY.BP_Interactable_Passives_Treasure_2", lambda state: state.has('Village13Left', player) and state.has('swim', player))
    fn("Village_13_GAMEPLAY.BP_SCR_LV1S_2021_2", lambda state: state.has('Village13Left', player))
    fn("Village_14_GAMEPLAY.BP_e2112_Ork", lambda state: state.has('Village14Bottom', player) and (state.has('LEDGE', player) or state.has('hook', player)))
    fn("Village_14_GAMEPLAY.BP_SCR_LV1L_2111_2", lambda state: state.has('Elder', player) and (state.has('slam', player) and (state.has('hook', player) or state.has('LEDGE', player) and state.has('sinner', player) or state.has('silva', player) and (state.has('djump', player) or state.has('dodge', player)) or state.has('champion', player) and (state.has('dash', player) or state.has('claw', player)) and (state.has('silva', player) or state.has('djump', player)))))
    fn("Village_14_GAMEPLAY.BP_SCR_LV2L_2110_3", lambda state: state.has('Elder', player) and (state.has('slam', player) and (state.has('hook', player) or state.has('3LEDGE', player) or state.has('FULLSILVA', player) or state.has('claw', player) and state.has('LEDGE', player))))
    fn("Village_15_GAMEPLAY.BP_SCR_LV1LL_0000_2", lambda state: state.has('Village15Left', player) and state.has('swim', player) and (state.has('claw', player) and (state.has('sinner', player) and (state.has('djump', player) or state.has('champion', player)) or state.has('dodge', player) and state.has('silva', player) or state.has('2LEDGE', player) and state.has('HORIZONTAL', player)) or state.has('hook', player) and (state.has('2LEDGE', player) or state.has('claw', player) and (state.has('LEDGE', player) or state.has('HORIZONTAL', player)))) or state.has('Village15Right', player) and state.has('claw', player) and state.has('djump', player) and state.has('silva', player))
    fn("Village_15_GAMEPLAY.BP_SCR_LV1M_2050_3", lambda state: state.has('Village15Right', player) and state.has('swim', player))
    fn("Village_15_GAMEPLAY.BP_SCR_LV2M_2050_2", lambda state: state.has('Village15Left', player) and state.has('swim', player))
    fn("Village_16_GAMEPLAY.BP_Interactable_Item_Tip4", lambda state: state.has('Village16Right', player))
    fn("Village_16_GAMEPLAY.BP_Interactable_Passives_Treasure_2", lambda state: state.has('Village16Right', player))
    
